extends Node

func _ready()->void:
	var game=load("res://main.tscn").instantiate();add_child(game)
	await get_tree().process_frame;await get_tree().process_frame
	game._reset_progression_state();game.intro_story_complete=true;game.encyclopedia_unlocked=true;game.habitat_unlocked=true;game.buyback_unlocked=true;game.total_play_count=3;game.formal_play_count=3
	game.discovered={"colorata":true,"laui":false};game.species_get_counts={"colorata":4};game.bests={"colorata":62.5};game.coins=2000;game._sync_arrangement_ui();game._update_play_ui()
	var ui=game.arrangement_ui
	assert(game.pot_catalog.size()>=3 and bool(game.owned_pots.get("starter_terracotta",false)))
	for pot_value in game.pot_catalog:
		for required_key in ["pot_id","display_name","image_path","price","unlock_condition","iap_product_id","placement_area","sort_order"]:assert(pot_value.has(required_key))
	assert(game.arrangement_button.visible)
	var available:Array=ui._available_species_entries("all");assert(available.size()==1 and str(available[0].species_id)=="colorata")
	print("ARRANGEMENT_CAMERA_PRE_TEST tutorial=",game._tutorial_fully_complete()," pan=",game.greenhouse_pan_x," button=",game.arrangement_button.visible)
	var normal_pan:float=float(game.greenhouse_pan_x);game._open_arrangements();print("ARRANGEMENT_CAMERA_OPEN_TEST active=",game.arrangement_mode_active," transition=",game.arrangement_transition_active," visible=",ui.visible);assert(game.arrangement_mode_active and game.arrangement_transition_active and not ui.visible)
	for status_control in game.greenhouse_status_controls:assert(not status_control.visible)
	await get_tree().create_timer(game.ARRANGEMENT_CAMERA_TRANSITION_SECONDS+.08).timeout
	print("ARRANGEMENT_CAMERA_ENTRY_TEST pan=",game.greenhouse_pan_x," target=",game.greenhouse_arrangement_view_x," visible=",ui.visible)
	assert(ui.visible and not game.arrangement_transition_active and is_equal_approx(game.greenhouse_pan_x,game.greenhouse_arrangement_view_x) and game.greenhouse_pan_x>=normal_pan)
	ui.close();assert(game.arrangement_mode_active and game.arrangement_transition_active)
	await get_tree().create_timer(game.ARRANGEMENT_CAMERA_TRANSITION_SECONDS+.08).timeout
	print("ARRANGEMENT_CAMERA_RETURN_TEST pan=",game.greenhouse_pan_x," active=",game.arrangement_mode_active)
	assert(not game.arrangement_mode_active and not game.arrangement_transition_active and game.greenhouse_pan_x<=game.greenhouse_normal_pan_max)
	for status_control in game.greenhouse_status_controls:assert(status_control.visible)
	ui.open_home();ui._start_new_arrangement();assert(ui.pot_select_page.visible)
	ui._select_editor_pot("starter_terracotta");assert(ui.editor_page.visible and str(ui.current_arrangement.pot_id)=="starter_terracotta")
	ui._add_species_to_editor("laui");assert(ui.editor_plants.is_empty())
	ui._add_species_to_editor("colorata");assert(ui.editor_plants.size()==1 and ui.selected_plant_index==0)
	var original_position:=Vector2(float(ui.editor_plants[0].x),float(ui.editor_plants[0].y));var plant_node:Control=ui.editor_plant_nodes[0]
	var down:=InputEventMouseButton.new();down.button_index=MOUSE_BUTTON_LEFT;down.pressed=true;down.position=ui.PLANT_CONTROL_SIZE*.5;ui._on_plant_gui_input(down,0,plant_node)
	var drag:=InputEventMouseMotion.new();drag.position=ui.PLANT_CONTROL_SIZE*.5+Vector2(38,24);ui._on_plant_gui_input(drag,0,plant_node)
	var up:=InputEventMouseButton.new();up.button_index=MOUSE_BUTTON_LEFT;up.pressed=false;up.position=drag.position;ui._on_plant_gui_input(up,0,plant_node)
	var moved_position:=Vector2(float(ui.editor_plants[0].x),float(ui.editor_plants[0].y));assert(moved_position.distance_to(original_position)>10.0 and not ui.drag_active)
	ui._adjust_selected_scale(.1);assert(is_equal_approx(float(ui.editor_plants[0].scale),1.1))
	var gesture_center:=Vector2(float(ui.editor_plants[0].x),float(ui.editor_plants[0].y));var scale_before_gesture:=float(ui.editor_plants[0].scale)
	ui._begin_editor_touch(0,gesture_center-Vector2(30,0));ui._begin_editor_touch(1,gesture_center+Vector2(30,0));ui._update_editor_touch(1,gesture_center+Vector2(50,15),Vector2(20,15))
	assert(float(ui.editor_plants[0].scale)>scale_before_gesture and absf(float(ui.editor_plants[0].rotation))>1.0)
	ui._end_editor_touch(1,gesture_center+Vector2(50,15));ui._end_editor_touch(0,gesture_center-Vector2(30,0))
	ui._flip_selected_plant();assert(bool(ui.editor_plants[0].flipped) and ui.editor_plant_nodes[0].get_node("PlantImage").scale.x<0.0)
	for rotation_step in range(24):ui._adjust_selected_rotation(15.0)
	assert(float(ui.editor_plants[0].rotation)>=0.0 and float(ui.editor_plants[0].rotation)<360.0)
	ui._add_species_to_editor("colorata");assert(ui.editor_plants.size()==2)
	ui.editor_plants[1]["x"]=ui.editor_plants[0].x;ui.editor_plants[1]["y"]=ui.editor_plants[0].y;ui._rebuild_editor_scene();gesture_center=Vector2(float(ui.editor_plants[0].x),float(ui.editor_plants[0].y))
	ui._begin_editor_touch(-1,gesture_center);ui._end_editor_touch(-1,gesture_center);var first_overlap_selection:int=int(ui.selected_plant_index)
	ui._begin_editor_touch(-1,gesture_center);ui._end_editor_touch(-1,gesture_center);assert(ui.selected_plant_index!=first_overlap_selection)
	ui._toggle_layer_panel();assert(ui.layer_panel.visible and ui.layer_list.get_child_count()==2);ui._select_from_layer_list(0);assert(ui.selected_plant_index==0 and not ui.layer_panel.visible)
	ui._select_plant(0);ui._change_selected_depth(1);assert(int(ui.editor_plants[0].z_index)>int(ui.editor_plants[1].z_index));ui._change_selected_depth(-1);assert(int(ui.editor_plants[0].z_index)<int(ui.editor_plants[1].z_index))
	ui._select_plant(1);ui._delete_selected_plant();assert(ui.editor_plants.size()==1)
	var get_before:Dictionary=game.species_get_counts.duplicate(true);var best_before:Dictionary=game.bests.duplicate(true);var discovered_before:Dictionary=game.discovered.duplicate(true)
	ui.editor_name.text="春の寄せ植え";ui._save_current_arrangement();assert(game.saved_arrangements.size()==1 and ui.viewer_page.visible and ui.viewer_plant_layer.get_child_count()==1 and ui.viewer_plant_layer.find_child("SelectionBorder",true,false)==null)
	assert(game.species_get_counts==get_before and game.bests==best_before and game.discovered==discovered_before)
	var saved:Dictionary=game.saved_arrangements[0];assert(saved.has("arrangement_id") and saved.has("name") and saved.has("pot_id") and saved.has("created_at") and saved.has("plants"));assert(saved.plants.size()==1)
	for plant_key in ["species_id","x","y","scale","rotation","flipped","z_index"]:assert(saved.plants[0].has(plant_key))
	assert(bool(saved.plants[0].flipped))
	var legacy_arrangement:Dictionary=game._normalize_arrangement({"arrangement_id":"legacy","name":"旧作品","pot_id":"starter_terracotta","plants":[{"species_id":"colorata","x":200,"y":250,"scale":1.0,"rotation":0.0,"z_index":0}]});assert(not bool(legacy_arrangement.plants[0].flipped))
	var saved_id:=str(saved.arrangement_id);game._save();game.saved_arrangements.clear();game._load_save();assert(game.saved_arrangements.size()==1 and str(game.saved_arrangements[0].arrangement_id)==saved_id)
	game._sync_arrangement_ui();ui._edit_arrangement(game.saved_arrangements[0]);ui.editor_name.text="春の寄せ植え・改";ui._save_current_arrangement();assert(game.saved_arrangements.size()==1 and str(game.saved_arrangements[0].name)=="春の寄せ植え・改")
	var coins_before:int=game.coins;game._on_pot_purchase_requested("cream_ceramic");assert(bool(game.owned_pots.get("cream_ceramic",false)) and game.coins==coins_before-900);game._on_pot_purchase_requested("cream_ceramic");assert(game.coins==coins_before-900)
	assert(game.species_get_counts==get_before and game.bests==best_before and game.discovered==discovered_before)
	ui.current_arrangement={"arrangement_id":"limit_test","name":"上限テスト","pot_id":"starter_terracotta","created_at":"test","plants":[]};ui._load_editor_from_current()
	for plant_index in range(ui.MAX_PLANTS_PER_ARRANGEMENT+3):ui._add_species_to_editor("colorata")
	assert(ui.editor_plants.size()==ui.MAX_PLANTS_PER_ARRANGEMENT and ui.add_plant_button.disabled)
	print("ARRANGEMENT_SMOKE_OK pots=",game.pot_catalog.size()," saved=",game.saved_arrangements.size()," max_plants=",ui.MAX_PLANTS_PER_ARRANGEMENT)
	get_tree().quit()
